<?php

namespace App\Models\Comercial;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AdmDocumentos extends Model
{
    use HasFactory;

    protected $table = 'admDocumentos';

    protected $fillable = [
        'CIDDOCUMENTO',
        'CIDDOCUMENTODE',
        'CIDCONCEPTODOCUMENTO',
        'CSERIEDOCUMENTO',
        'CFOLIO',
        'CFECHA',
        'CIDCLIENTEPROVEEDOR',
        'CRAZONSOCIAL',
        'CRFC',
        'CIDAGENTE',
        'CFECHAVENCIMIENTO',
        'CFECHAPRONTOPAGO',
        'CFECHAENTREGARECEPCION',
        'CFECHAULTIMOINTERES',
        'CIDMONEDA',
        'CTIPOCAMBIO',
        'CREFERENCIA',
        'COBSERVACIONES',
        'CNATURALEZA',
        'CIDDOCUMENTOORIGEN',
        'CPLANTILLA',
        'CUSACLIENTE',
        'CUSAPROVEEDOR',
        'CAFECTADO',
        'CIMPRESO',
        'CCANCELADO',
        'CDEVUELTO',
        'CIDPREPOLIZA',
        'CIDPREPOLIZACANCELACION',
        'CESTADOCONTABLE',
        'CNETO',
        'CIMPUESTO1',
        'CIMPUESTO2',
        'CIMPUESTO3',
        'CRETENCION1',
        'CRETENCION2',
        'CDESCUENTOMOV',
        'CDESCUENTODOC1',
        'CDESCUENTODOC2',
        'CGASTO1',
        'CGASTO2',
        'CGASTO3',
        'CTOTAL',
        'CPENDIENTE',
        'CTOTALUNIDADES',
        'CDESCUENTOPRONTOPAGO',
        'CPORCENTAJEIMPUESTO1',
        'CPORCENTAJEIMPUESTO2',
        'CPORCENTAJEIMPUESTO3',
        'CPORCENTAJERETENCION1',
        'CPORCENTAJERETENCION2',
        'CPORCENTAJEINTERES',
        'CTEXTOEXTRA1',
        'CTEXTOEXTRA2',
        'CTEXTOEXTRA3',
        'CFECHAEXTRA',
        'CIMPORTEEXTRA1',
        'CIMPORTEEXTRA2',
        'CIMPORTEEXTRA3',
        'CIMPORTEEXTRA4',
        'CDESTINATARIO',
        'CNUMEROGUIA',
        'CMENSAJERIA',
        'CCUENTAMENSAJERIA',
        'CNUMEROCAJAS',
        'CPESO',
        'CBANOBSERVACIONES',
        'CBANDATOSENVIO',
        'CBANCONDICIONESCREDITO',
        'CBANGASTOS',
        'CUNIDADESPENDIENTES',
        'CTIMESTAMP',
        'CIMPCHEQPAQ',
        'CSISTORIG',
        'CIDMONEDCA',
        'CTIPOCAMCA',
        'CESCFD',
        'CTIENECFD',
        'CLUGAREXPE',
        'CMETODOPAG',
        'CNUMPARCIA',
        'CCANTPARCI',
        'CCONDIPAGO',
        'CNUMCTAPAG',
        'CIDPROYECTO',
        'CIDCUENTA',
        'CGUIDDOCUMENTO',
        'CUSUARIO',
        'CTRANSACTIONID',
        'CIDCOPIADE',
        'CVERESQUE'
    ];
}
